[2024-07-23T14:21:41.740+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-23T14:21:41.749+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: welcome_ais_dag.print_weather scheduled__2024-07-22T11:00:00+00:00 [queued]>
[2024-07-23T14:21:41.751+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: welcome_ais_dag.print_weather scheduled__2024-07-22T11:00:00+00:00 [queued]>
[2024-07-23T14:21:41.751+0000] {taskinstance.py:2306} INFO - Starting attempt 8 of 8
[2024-07-23T14:21:41.757+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): print_weather> on 2024-07-22 11:00:00+00:00
[2024-07-23T14:21:41.759+0000] {standard_task_runner.py:64} INFO - Started process 258 to run task
[2024-07-23T14:21:41.760+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'welcome_ais_dag', 'print_weather', 'scheduled__2024-07-22T11:00:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/welcome_dag.py', '--cfg-path', '/tmp/tmp1wlhm03z']
[2024-07-23T14:21:41.761+0000] {standard_task_runner.py:91} INFO - Job 29: Subtask print_weather
[2024-07-23T14:21:41.777+0000] {task_command.py:426} INFO - Running <TaskInstance: welcome_ais_dag.print_weather scheduled__2024-07-22T11:00:00+00:00 [running]> on host 3ca61712785c
[2024-07-23T14:21:41.800+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='welcome_ais_dag' AIRFLOW_CTX_TASK_ID='print_weather' AIRFLOW_CTX_EXECUTION_DATE='2024-07-22T11:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='8' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-22T11:00:00+00:00'
[2024-07-23T14:21:41.800+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-23T14:21:41.992+0000] {logging_mixin.py:188} INFO - json full: <Response [200]>
[2024-07-23T14:21:41.993+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-23T14:21:41.994+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/welcome_dag.py", line 25, in print_weather
    tz_id = json_full.location.tz_id
            ^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'location'
[2024-07-23T14:21:42.002+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=welcome_ais_dag, task_id=print_weather, run_id=scheduled__2024-07-22T11:00:00+00:00, execution_date=20240722T110000, start_date=20240723T142141, end_date=20240723T142142
[2024-07-23T14:21:42.016+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 29 for task print_weather ('dict' object has no attribute 'location'; 258)
[2024-07-23T14:21:42.030+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-23T14:21:42.039+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-23T14:21:42.040+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
